### PR TITLE
Make changes to fix several daemon related issues

### LINKED ISSUE #1241: Ctrl+C may kill daemon background process on Windows
**Steps to Reproduce**
1. Ensure the daemon server is _not_ running
2. Run a command with the daemon client binary that prompts for input
    ```
    $ zowe jobs ls jobs
    Starting a background process to increase performance ...
    Enter the host name of your service (will be hidden):
    ```
3. Press Ctrl+C to terminate

**Actual Behavior**
Run `ps aux | grep zowe` and the daemon server is not running anymore.

**Expected Behavior**
The daemon server should still be running. Ctrl+C should only trigger an ECONNRESET without killing the background process. This is the behavior you see if you repeat the steps above but for `#1` ensure the daemon server _is_ running.

### LINKED ISSUE #1277: Daemon mode prevents from exiting command prompt
Reported by @davidkjackson54:

> if I issue this command:
> ```
> C:\Users\XXX>zowe -V
> Starting a background process to increase performance ...
> 7.0.0-next.202112102143
> 
> C:\Users\XXX>exit
> ```
>
> it hangs...  It never closes the Windows command prompt window,. I have to click the upper right and force it closed.That looks like a bug to me.

This may be a limitation, not a bug we can fix, since Windows doesn't support forking processes like Unix does. If so, perhaps we should document it as a known limitation on Windows.

### LINKED ISSUE #1309: Daemon termination should be consistent on all platforms
When the Zowe CLI daemon is started on Windows, the daemon continues to run until the user closes the console window which started the daemon.

On Linux, the daemon continues to run until the user logs out.

Daemon behavior would be more consistent if the daemon terminated the same way on all platforms.

### LINKED ISSUE #1379: Allow Daemon Colorize Setting
When I use Zowe CLI, I manually start the daemon to preserve colorization.  To do this I:
1. `set ZOWE_USE_DAEMON=false`
1. `start zowe --daemon`
1. `set ZOWE_USE_DAEMON=true`
1. use zowe daemon as usual but with colors 😎 
 
files

Can there be some flag or setting such that when I know I'm in an environment where I know colors work, daemon will start automatically with colors?  This would help me eliminate steps 1 - 3 😄

### LINKED ISSUE #1701: Progress bar not working in zowe deamon mode for some terminal types
When using the progress API to display task progress inside a Zowe CLI plugin, if the command executes in Zowe deamon mode, in some terminal types the progress bar is not refreshed, but instead printed repeatedly (Example from Broadcom Endevor plugin):

O | Retrieving 3 elements..←[0K←[1G __________| 0%  o | Retrieving 3 elements..←[0K←[1G __________| 0%  - | Retrieving 3 elements..←[0K←[1G __________| 0%  o | Retrieving 3 elements..←[0K←[1G __________| 0%  O | Retrieving 3 elements..←[0K←[1G __________| 0%  0 | Retrieving 3 elements..←[0K←[1G __________| 0%  ) | Retrieving 3 elements..←[0K←[1G __________| 0%  | | Retrieving 3 elements..←[0K←[1G __________| 0%  ( | Retrieving 3 elements..←[0K←[1G __________| 0%  0 | Retrieving 3 elements..←[0K←[1G __________| 0%  O | Retrieving 3 elements..←[0K←[1G __________| 0%  o | Retrieving 3 elements..←[0K←[1G __________| 0%  - | Retrieving 3 elements..←[0K←[1G __________| 0%  o | Retrieving 3 elements..←[0K←[1G __________| 0%  O | Retrieving 3 elements..←[0K←[1G __________| 0%  0 | Retrieving 3 elements..←[0K←[1G __________| 0%  ) | Retrieving 3 elements..←[0K←[1G __________| 0%  | | Retrieving 3 elements..←[0K←[1G __________| 0%  ( | Retrieving 3 elements..←[0K←[1G __________| 0%  0 | Retrieving 3 elements..←[0K←[1G __________| 0%  O | Retrieving 3 elements..←[0K←[1G __________| 0%  o | Retrieving 3 elements..←[0K←[1G __________| 0%  - | Retrieving 3 elements..←[0K←[1G __________| 0%  o | Retrieving 3 elements..←[0K←[1G __________| 0%  O | Retrieving 3 elements..←[0K←[1G __________| 0%  0 | Retrieving 3 elements..←[0K←[1G __________| 0%  ) | Retrieving 3 elements..←[0K←[1G __________| 0%  | | Retrieving 3 elements..←[0K←[1G __________| 0%  ( | Retrieving 3 elements..←[0K←[1G __________| 0%  0 | Retrieving 3 elements..←[0K←[1G __________| 0%  O | Retrieving 3 elements..←[0K←[1G __________| 0%  o | Retrieving 3 elements..←[0K←[1G __________| 0%  - | Retrieving 3 elements..←[0K←[1G __________| 0%  o | Retrieving 3 elements..←[0K←[1G __________| 0%  O | Retrieving 3 elements..←[0K←[1G __________| 0%  0 | Retrieving 3 elements..←[0K←[1G __________| 0%  ) | Retrieving 3 elements..←[0K←[1G ███_______| 33%  | | Retrieving 3 elements..←[0K←[1G ███████___| 66%  ( | Retrieving 3 elements..←[0K←[1G ███████___| 66%  0 | Retrieving 3 elements..←[0K←[1G ███████___| 66%  O | Retrieving 3 elements..←[0K←[1G ███████___| 66%  o | Retrieving 3 elements..←[0K←[1G ███████___| 66%  - | Retrieving 3 elements..←[0K←[1G ███████___| 66%  o | Retrieving 3 elements..←[0K←[1G ██████████| 100%    | Complete←[0K←[2K←[1G←[2K←[1G←[1G ██████████| 100%    | Complete←[0K←[2K←[1G←[2K←[1G←[1G ██████████| 100%    | Complete←[0K←[2K←[1G←[2K←[1G←[1G ██████████| 100%    | Complete←[0K←[2K←[1G←[2K←[1G←[1G ██████████| 100%    | Complete←

Issue reproduced in Windows Command prompt and in Git Bash. 
Works correctly in VSC powershell.

### PR DESCRIPTION
**Pull request by awharn**
Fixes #1241 
Fixes #1277
Fixes #1309 
Makes a change to spawn the daemon as its own process group without a console window, preventing CTRL+C from killing the process and preventing a terminal from spawning. Also spawns the process under the user namespace, which causes it to terminate when the user logs out.

Fixes #1379
Fixes #1701  
Adds crates to enable ANSI escape characters, including colors, in command prompt and detect the supported colors of the terminal. Passes that information to Imperative using the FORCE_COLOR environment variable if it is not defined in the current context. If it is defined in the current context, passes that along instead, fixing accessibility. In the event ANSI escape characters cannot be enabled in the current terminal, forces FORCE_COLOR to 0 (disabling color) regardless of the environment.

~~⚠️ Requires zowe/imperative#977 to be merged and used ⚠️~~

Note: If someone or something kills the parent process of the daemon (i.e. command prompt), the daemon will stop. Closing the command prompt with the X button allows the daemon to continue working, but **forcefully** ending the parent task in Task Manager will kill the daemon process.

### CODE REVIEW

File: zowex/src/util.rs [hunk 1]
```diff
@@ -134,9 +140,27 @@ pub fn util_get_socket_string() -> Result<String, i32> {
...
+    if !util_enable_ansi() {
+        environment.insert(String::from("FORCE_COLOR"), String::from("0"));
+    }
+
+    environment
+}
+
+pub fn util_get_color_env() -> HashMap<String, String> {
+    let mut temp_map = HashMap::new();
+    temp_map.insert(String::from("FORCE_COLOR"), String::from(util_terminal_supports_color().to_string()));
```
Comment (traeok) [inline zowex/src/util.rs:162]: `util_terminal_supports_color().to_string()` is already a `String`, can remove `String::from` here

File: zowex/src/util.rs [hunk 2]
```diff
@@ -21,6 +21,12 @@ use home::home_dir;
 extern crate pathsearch;
 use pathsearch::PathSearcher;
 
+extern crate supports_color;
+use supports_color::Stream;
+
+extern crate yansi;
+use yansi::Paint;
```
Comment (traeok) [inline zowex/src/util.rs:28]: No need for changes, just curious: why `yansi` over `ansi_term`?

**Review by traeok — APPROVED** [review]
LGTM, thanks @awharn !

File: zowex/src/proc.rs [hunk 3]
```diff
@@ -269,22 +271,37 @@ fn read_pid_for_user() -> Option<sysinfo::Pid> {
...
+
+    // Uses creation flags from https://learn.microsoft.com/en-us/windows/win32/procthread/process-creation-flags
+    // Flags are CREATE_NO_WINDOW, CREATE_NEW_PROCESS_GROUP, and CREATE_UNICODE_ENVIRONMENT
+    #[cfg(target_family = "windows")]
     match Command::new(njs_zowe_path)
         .arg(daemon_arg)
         .stdout(Stdio::null())
         .stderr(Stdio::null())
+        .creation_flags(0x08000600)
         .spawn()
```
Comment (t1m0thyj) [inline zowex/src/proc.rs:305]: Would something like this work to consolidate the code?
```rust
    let mut command = Command::new(njs_zowe_path)
        .arg(daemon_arg)
        .stdout(Stdio::null())
        .stderr(Stdio::null());
    #[cfg(target_family = "windows")]
    command.creation_flags(0x08000600);

    command.spawn()
    {
        Ok(_unused) => { /* nothing to do */ }
        Err(error) => {
            println!(
                "Failed to start the following process:\n    {} {}",
                njs_zowe_path, daemon_arg
            );
            println!("Due to this error:\n    {}", error);
            std::process::exit(EXIT_CODE_CANNOT_START_DAEMON);
        }
    };
```

Comment (awharn) [reply zowex/src/proc.rs:305]: I cannot do this, because it would involve reassigning `command`:

`command = command.creation_flags(0x08000600)`, and attributes on expressions such as that are not currently supported in rust, and are experimental at this time.

Comment (t1m0thyj) [reply zowex/src/proc.rs:305]: I believe the fact that `command.creation_flags` returns a command object is purely for convenience, so that multiple `command.XXX` functions can be chained together. The original command object gets mutated so it's not required to reassign the command variable to a new value.

Also there were a few mistakes in the code snippet I posted - sorry about that 😢 Updated the snippet in my above comment and it built for me locally without errors.

Comment (awharn) [reply zowex/src/proc.rs:305]: I did test this yesterday with @traeok, and spawning it like this still caused it to be spawned as a subprocess of the current terminal.

Comment (traeok) [reply zowex/src/proc.rs:305]: I thought we had tried it without reassigning command, and not sure why it wasn't working but as @awharn mentioned the process was still spawning as a subprocess of the terminal.

But, we can change the argument for `creation_flags` to `0x08000200` as any argument passed here will alway's be OR'ed with `CREATE_UNICODE_ENVIRONMENT`:
https://doc.rust-lang.org/stable/std/os/windows/process/trait.CommandExt.html#tymethod.creation_flags

Comment (awharn) [reply zowex/src/proc.rs]: I don't know what changed between yesterday and today, but it seems to work now. 🤷

File: zowex/src/proc.rs [hunk 4]
```diff
@@ -269,23 +271,23 @@ fn read_pid_for_user() -> Option<sysinfo::Pid> {
...
-
     let daemon_arg = LAUNCH_DAEMON_OPTION;
-    match Command::new(njs_zowe_path)
-        .arg(daemon_arg)
-        .stdout(Stdio::null())
-        .stderr(Stdio::null())
-        .spawn()
+    let mut cmd = Command::new(njs_zowe_path);
+    
+    // Uses creation flags from https://learn.microsoft.com/en-us/windows/win32/procthread/process-creation-flags
```
Comment (gejohnston) [inline zowex/src/proc.rs:281]: I am very disappointed that I did not find and use these techniques during the last round of daemon updates. Nicely done!

**Review by gejohnston — APPROVED** [review]
Looks good.

**Review by zFernand0 — APPROVED** [review]
Code changes LGTM! 😋 

I'm happy to get color on the Daemon now! 🥳
