### PR TITLE
Make changes to support #2598

### LINKED ISSUE #2596: TSO SDK does not export `IIssueTsoCmdOpts` interface
The `issueTsoCommand` function has been deprecated in favor of `issueTsoCmd`, which uses the `IIssueTsoCmdOpts` interface. This interface should be exported from the TSO SDK package for extenders to use.

### LINKED ISSUE #2598: Setting log level to TRACE should not display credentials
See https://github.com/eclipse-che4z/che-che4z-lsp-for-hlasm/issues/305#issuecomment-3201069010. A common step when debugging ZE is to set log level to TRACE. This may result in B64-encoded credentials being logged. Although we warn about this in Zowe docs, it is still unexpected behavior that we should try to avoid.

### PR DESCRIPTION
**Pull request by awharn**
**What It Does**

Fixes logging basic credentials in the Authorization header in the AbstractRestClient
Fixes logging cookie based authentication in the AbstractRestClient
Fixes exports for the `IIssueTsoCmdOpts`, `IStartTsoAppParms`, and `ITsoAppCommunicationParms` interfaces
Fixes a daemon audit failure.
Fixes a secrets SDK audit failure.
Fixes #2598
Fixes #2596 

**How to Test**

Run a dataset list command in trace logger mode with an incorrect port number. Observe the Imperative logs.
Switch to this branch, and perform the same actions. Observe the issue is no longer present.

**Review Checklist**
I certify that I have:
- [x] updated the changelog
- [x] manually tested my changes
- [x] added/updated automated unit/integration tests
- [x] created/ran system tests (provide build number if applicable) - 1367 & 1368
- [x] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

**Additional Comments**

### CODE REVIEW

**Comment by awharn** [comment]
Ignore the changelog failure - a linter error from another PR was fixed in this PR, but has no customer impact whatsoever.

File: packages/imperative/src/censor/src/Censor.ts [hunk 1]
```diff
@@ -316,6 +326,49 @@ export class Censor {
...
+
+    /**
+     * Copy and censor over an object
+     * @param {Record<string, any>} data - the data to censor
+     * @returns {Record<string, any>} - the censored data
+     */
+    private static mCensorObject(data: Record<string, any>, secureValues: any[]): Record<string, any> {
+        const newData: Record<string, any> = {};
+        for (const [key, value] of Object.entries(data)) {
+            if (this.CENSORED_OPTIONS.includes(key) || secureValues.includes(value)) {
```
Comment (gejohnston) [inline packages/imperative/src/censor/src/Censor.ts:379]: Trying to clarify my understanding: Is the intention to censor the value of a non-secure property if it happens to have the same value as another property which is defined as secure?

If not, then I misinterpreted, and that's fine.

If I am correct, then it could censor the values of some properties that are not marked as secure. I think this would also be ok since it guarantees the censoring of a known secure value regardless of what other properties happen to have that same value.

Comment (awharn) [reply packages/imperative/src/censor/src/Censor.ts:379]: This does the latter, and will censor a non-secure property (or, in this case, value in an object) if it is known to be secure somewhere. This is because `host` can be considered a secure value, but may be under the key `hostname` in the session. This is also true for custom token headers (i.e. X-API-Token). Since any object can be passed in for censoring, we don't know if the key will necessarily exactly match the name of the property.

**Comment by awharn** [comment]
Re-requested review due to the enhancement of allowing extenders to define additional headers to censor.

File: packages/imperative/src/rest/src/client/AbstractRestClient.ts [hunk 2]
```diff
@@ -646,7 +647,7 @@ export abstract class AbstractRestClient {
             return false;
         }
 
-        this.log.trace("Using cookie authentication with token %s", this.session.ISession.tokenValue);
+        this.log.trace("Using cookie authentication with token");
```
Comment (t1m0thyj) [inline packages/imperative/src/rest/src/client/AbstractRestClient.ts]: Thanks for the change, we definitely don't want to log token value here 😋 

(nitpick) Should we log token type instead for debugging purposes?
```suggestion
        this.log.trace("Using cookie authentication with token type %s", this.session.ISession.tokenType);
```

File: packages/imperative/src/censor/src/Censor.ts [hunk 3]
```diff
@@ -55,6 +59,22 @@ export class Censor {
...
+        return Array.from(censoredList);
+    }
+
+    public static get CUSTOM_CENSORED_HEADERS(): string[] {
+        const censoredList = new Set<string>();
+        for (const header of this.INTERNAL_CUSTOM_CENSORED_HEADERS) {
+            censoredList.add(header);
+        }
+        return Array.from(censoredList);
+    }
```
Comment (traeok) [inline packages/imperative/src/censor/src/Censor.ts]: I can see why this logic pattern is needed for `DEFAULT_CENSORED_OPTIONS` (in order to add the `kebabCase` format for the option), but it feels redundant here:

- Every time this getter is called, it has O(n) time complexity
- Uses a loop to copy array elements into the Set (no real de-duplication benefit here, since you already skip duplicates in the `addCensoredHeader` implementation on line 187)

Thoughts on spreading the array instead?


```suggestion
    public static get DEFAULT_CENSORED_HEADERS(): string[] {
        return [...this.MAIN_CENSORED_HEADERS];
    }

    public static get CUSTOM_CENSORED_HEADERS(): string[] {
        return [...this.INTERNAL_CUSTOM_CENSORED_HEADERS];
    }
```

This approach maintains the same behavior (doesn't mutate the original array), while being faster and avoiding memory allocations.

File: packages/imperative/src/censor/src/Censor.ts [hunk 4]
```diff
@@ -162,6 +186,19 @@ export class Censor {
         }
     }
 
+    /**
+     * Add a header to censor
+     * @param {string} header - The name of the header to censor
+     */
+    public static addCensoredHeader(header: string) {
+        if (header != null) {
+            if (!this.INTERNAL_CUSTOM_CENSORED_HEADERS.includes(header)) {
```
Comment (traeok) [inline packages/imperative/src/censor/src/Censor.ts:187]: see `includes` check mentioned in above comment

File: packages/imperative/src/censor/src/Censor.ts (hunk 3 above)
Comment (awharn) [reply packages/imperative/src/censor/src/Censor.ts]: Love the idea, thanks for the suggestion. You're absolutely right in this case. 😄

File: packages/imperative/src/rest/src/client/AbstractRestClient.ts (hunk 2 above)
Comment (awharn) [reply packages/imperative/src/rest/src/client/AbstractRestClient.ts]: I am going to do a sensitive value check before we do, but sure.

**Review by t1m0thyj — APPROVED** [review]
LGTM, thanks @awharn!

**Review by traeok — APPROVED** [review]
Thanks again for the fix and for quickly addressing feedback 🙏
