### PR TITLE
Prevent postinstall failure when a bad config file exists

### LINKED ISSUE #1198: CLI fails to install when there is invalid config JSON
**Steps**
Navigate to an empty directory and run:
1. `npm init -y`
2. `echo "invalid JSON" > zowe.config.json`
3. `npm install @zowe/cli@next`

**Actual Behavior**: Can't install Zowe CLI when there is an invalid zowe.config.json file present, since the post-install script fails to run.

**Expected Behavior**: Zowe CLI should install successfully, and wait to tell me about the invalid zowe.config.json until I run `zowe`.

### PR DESCRIPTION
**Pull request by awharn**
Fixes #1198 by preventing config files from being loaded during Imperative initialization, allowing the validate command to be run.

### CODE REVIEW

**Review by gejohnston — APPROVED** [review]

File: packages/cli/src/main.ts [hunk 1]
```diff
@@ -32,7 +33,9 @@ const config: IImperativeConfig = {
     try {
         timingApi.mark("BEFORE_INIT");
 
-        if(process.argv.includes("--daemon")) { config.daemonMode = true; }
+        if(process.argv.includes("--daemon") || (process.env.npm_lifecycle_event != null && process.env.npm_lifecycle_event === "postinstall")) {
```
Comment (zFernand0) [inline packages/cli/src/main.ts:36]: Does `npm_lifecycle_event === "postinstall"`  cover both cases ?
`npm_lifecycle_event != null` and `npm_lifecycle_event === "postinstall"`

**Review by zFernand0 — DISMISSED** [review]
LGTM, just left one comment :yum:

**Review by zFernand0 — DISMISSED** [review]
Thank you!

**Review by t1m0thyj — DISMISSED** [review]

**Review by gejohnston — DISMISSED** [review]

**Review by t1m0thyj — APPROVED** [review]

**Review by gejohnston — APPROVED** [review]
